### ISSUE TITLE
[BUG Possibly} MBIN file conflicting info from different commands

### ISSUE THREAD

**Issue by LeeC2202** [monkeyman192/MBINCompiler#116] opened 2019-03-27 20:24 UTC
**Describe the bug**
I am trying to examine the contents of a file used in a mod, as the mod hasn't been updated to 1.77. The file is "GCDEBUGOPTIONS.GLOBAL.MBIN". If I drag that file onto mbincompiler I get the error shown in log 1. If I try to use the **version** command in a command prompt, I get the error shown in log 2.

Is there something else that is used to decompile/compile these mbin files? Or is it possible the mod maker built mbincompiler on their own, so possibly has a version that is incompatible with any other version of mbincompiler?

I obviously don't want to log this as a bug here, if it has been caused by the actions of someone using an alternate mbin decompiler, I just wasn't aware of there being another one, so I was a bit confused.

**Expected behavior**
Either GCDEBUGOPTIONS.GLOBAL.MBIN to be decompiled with drag & drop, or for version number to be shown when using the "version" commandline option.

**Steps To Reproduce**
Drag GCDEBUGOPTIONS.GLOBAL.MBIN onto mbincompiler.exe to get the error in Log 1
use "mbincompiler version GCDEBUGOPTIONS.GLOBAL.MBIN" in a command prompt, to get the error shown in Log 2

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: v1.77.0.2
 - NMS Game Version or Steam Build Number: 1.77
 - MBIN File: GCDEBUGOPTIONS.GLOBAL.MBIN
 - MBIN File Version: 0.0.0.0

**Additional Information**
I know NMS modding seems a bit of a drain on time and resources and as a modder for other games, I know how irritating it can be to deal with problems like this. If this is something that is involving more effort than it's worth, I completely understand if these bugs aren't ones you want to fix. If I don't have these mods working, it's a minor issue at worst, I don't see many other issues being raised, so maybe NMS modding is on its way out.

[MBINCompiler (1).log](https://github.com/monkeyman192/MBINCompiler/files/3015102/MBINCompiler.1.log)
[MBINCompiler (2).log](https://github.com/monkeyman192/MBINCompiler/files/3015104/MBINCompiler.2.log)

**Comment by GaticusHax** [comment] 2019-03-27 21:02
If the MBIN file version reports 0.0.0.0 and you know it is not up-to-date, it means it is very old.
All MBIN files compiled with MBINCompilersince about v1.2 will include an embedded version number.
You will have to figure out what version is it meant for and try to find the corresponding version of MBINCompiler.

It's also possible the file was manually modified with a hex editor. Either way, if you can identify what version the MBIN belongs to, the appropriate version of MBINCompiler should handle it.

I'm closing this issue as it is not a bug.
If you need more help, it's best to visit the [NMS Modding discord server](https://discordapp.com/invite/3Ytkxss). Have fun!

**Closed as completed by GaticusHax** 2019-03-27 21:02 UTC

**Comment by LeeC2202** [comment] 2019-03-27 22:49
No problem... the file was from August 2018 btw https://nomansskymods.com/mods/ship-slots-overhaul/

**Comment by GaticusHax** [comment] 2019-03-27 23:09
You should try the MBINCompiler releases from around that time then. That would be somewhere around v1.53 to v1.58. Check the [Releases](https://github.com/monkeyman192/MBINCompiler/releases) section.
