### ISSUE TITLE
Failed decompilation with Desolation update: PROCEDURALPRODUCTTABLE.MBIN

### ISSUE THREAD

**Issue by Khaoz-Topsy** [monkeyman192/MBINCompiler#247] opened 2020-07-16 17:23 UTC
**Describe the bug**
Failed decompilation with Desolation update.

**Expected behavior**
Generate EXML from MBIN file

**Specs (please complete the following information, if applicable):**
 - MBINCompiler Version: v2.51.0-pre1
 - MBIN File: PROCEDURALPRODUCTTABLE.MBIN

**Additional Information**
```
[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: MBIN	version:	0.0.0.0	guid:	8DA992F13A2F604A	template:	cGcProceduralProductTable
  [EXPECTED INFO]: GUID: 1D20382C6544FD00
  

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed to read GcProceduralProductTable from MBIN.
[InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0x8E8

   at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
```

**Comment by monkeyman192** [comment] 2020-07-16 23:14
Closing as a duplicate of #249

**Closed as completed by monkeyman192** 2020-07-16 23:14 UTC
Labels: bug
