### ISSUE TITLE
Failed decompilation with Desolation update: EXPERIENCESPAWNTABLE.MBIN

### ISSUE THREAD

**Issue by Christianwidjaya** [monkeyman192/MBINCompiler#244] opened 2020-07-16 15:17 UTC
**Describe the bug**
decompile fails, before desolate update were fine

**Expected behavior**
Decompile MBIN properly

**Steps To Reproduce**
1. Trying to decompile

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: 2.51
 - NMS Game Version or Steam Build Number: 5285142
 - MBIN File: EXPERIENCESPAWNTABLE.MBIN
 - MBIN File Version: 0.0.0.0?

**Additional Information**
Were fine before desolation update

_Attachments:_
[VERSION]: MBINCompiler v2.51.0.1
[ARGS]: "convert" "-y" "-f" "D:\Steam\steamapps\common\No Man's Sky\modding\Project\RealisticSpaceCombat\METADATA\SIMULATION\SCENE\EXPERIENCESPAWNTABLE.MBIN"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: D:\Steam\steamapps\common\No Man's Sky\modding\Project\RealisticSpaceCombat\METADATA\SIMULATION\SCENE\EXPERIENCESPAWNTABLE.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	2A636898595D254E	template:	cGcExperienceSpawnTable
  [EXPECTED INFO]: GUID: 882C78A752331FE3
  

[ERROR]: [MbinException]: Failed to read GcExperienceSpawnTable from MBIN.
  [InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0x2770
  
  [INFO]: D:\Steam\steamapps\common\No Man's Sky\modding\Project\RealisticSpaceCombat\METADATA\SIMULATION\SCENE\EXPERIENCESPAWNTABLE.MBIN
[INFO]: MBIN	version:	0.0.0.0	guid:	2A636898595D254E	template:	cGcExperienceSpawnTable at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
  

[INFO]: 0 files converted.

[INFO]: 1 FILES FAILED.

  [ERROR]: Failed to read GcExperienceSpawnTable from MBIN.
  [FILE]: D:\Steam\steamapps\common\No Man's Sky\modding\Project\RealisticSpaceCombat\METADATA\SIMULATION\SCENE\EXPERIENCESPAWNTABLE.MBIN
  
[INFO]: 1 WARNINGS.

  [WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [FILE]: D:\Steam\steamapps\common\No Man's Sky\modding\Project\RealisticSpaceCombat\METADATA\SIMULATION\SCENE\EXPERIENCESPAWNTABLE.MBIN
  
[INFO]: TIME: 0,058 seconds

**Comment by monkeyman192** [comment] 2020-07-16 23:17
Closing as a duplicate of #249

**Closed as completed by monkeyman192** 2020-07-16 23:17 UTC
Labels: bug
