### ISSUE TITLE
Failed decompilation with Desolation update: DAMAGETABLE.MBIN

### ISSUE THREAD

**Issue by Christianwidjaya** [monkeyman192/MBINCompiler#245] opened 2020-07-16 15:23 UTC
Describe the bug
decompile fails, before desolate update were fine

Expected behavior
Decompile MBIN properly

Steps To Reproduce

Trying to decompile
Specs (please complete the following information, if applicable):

libMBIN (MBINCompiler) Version: 2.51
NMS Game Version or Steam Build Number: 5285142
MBIN File: DAMAGETABLE.MBIN
MBIN File Version: 0.0.0.0?
Additional Information
Were fine before desolation update

Attachments:
[VERSION]: MBINCompiler v2.51.0.1
[ARGS]: "convert" "./project/RealisticSpaceCombat/metadata\reality\tables"

If you encounter any errors, please submit a bug report and include this log file.
Please check that there isn't already a similar issue open before creating a new one.
https://github.com/monkeyman192/MBINCompiler/issues

[INFO]: Auto-Detected --input-format=MBIN
[INFO]: --input-format=MBIN --output-format=EXML

[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: D:\Steam\steamapps\common\No Man's Sky\modding\project\RealisticSpaceCombat\metadata\reality\tables\DAMAGETABLE.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	1E31FDC16D19BCCB	template:	cGcPlayerDamageTable
[EXPECTED INFO]: GUID: 8E78ABF98EBBAF65

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed serializing GcPlayerDamageTable to EXML.
[InvalidOperationException]: There was an error generating the XML document.
[ArgumentException]: '', hexadecimal value 0x01, is an invalid character.

   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)

**Comment by HolterPhylo** [comment] 2020-07-16 20:27
Please STOP creating Issues for MBINCompiler failure to decompile files for NMS 2.6.  MBINCompiler as NOT been updated yet!

**Comment by monkeyman192** [comment] 2020-07-16 23:17
Closing as a duplicate of #249

**Closed as completed by monkeyman192** 2020-07-16 23:17 UTC
Labels: bug
