### ISSUE TITLE
Possible compiler/gethub malware

### ISSUE THREAD

**Issue by Gudskriger** [monkeyman192/MBINCompiler#443] opened 2022-03-11 21:34 UTC
**Describe the bug**
When I download the latest version of MBINCompiler:
a) Windows Defender immediately quarantines MBINCompiler.exe, reporting a malware app called "Program:Win32/Uwamson.A!ml".
b) If I tell it to 'restore', it restores MBINCompiler.exe.  However, if I then execute it, as in "MBINCompiler.exe version", I get an immediate abnormal program termination.

This problem does not occur with the previous version of MBINCompiler (MBINCompiler v3.82.0-pre1).

**Expected behavior**
I expect to be able to download the latest MBINCompiler, not have Windows generate a Threat Protection event, and have the program execute correctly.

**Steps To Reproduce**
1. Go to 'https://github.com/monkeyman192/MBINCompiler/releases'
2. Click on 'MBINCompiler.exe', to trigger a download.
3. Wait a couple of minutes, for Windows Defender to trigger and detect the problem.
4. See error, via the Windows 'Virus and Threat Protection / Protection History' page.

**Specs (please complete the following information, if applicable):**
 - libMBIN (MBINCompiler) Version: v3.82.0-pre2
 - NMS Game Version or Steam Build Number: 8302761

**Comment by monkeyman192** [comment] 2022-03-12 02:02
Hmmm, interesting. I have just downlaoded the same exe from the releases and scanned it with Trend Micro and it finds nothing suspicious. Windows defender also complains but that's just because it's an exe downloaded from the internet.
Maybe do a system scan and see if you have gotten the malware from elsewhere and it infected some other files.
I think I'll close this as I certainly can't reproduce this, and I have had no other reports from any other users of this issue, so I think it is your machine sorry.

**Closed as completed by monkeyman192** 2022-03-12 02:02 UTC
Labels: bug

**Comment by jefuslives** [comment] 2022-03-23 05:10
I am also getting this issue in v3.82.0-pre2.  Windows defender is flagging the MBinCompiler.exe as malware Win32/Uwamson.A!ml
