### ISSUE TITLE
Failed decompilation with Desolation update: _BASE_1.ENTITY.MBIN

### ISSUE THREAD

**Issue by daheise** [monkeyman192/MBINCompiler#239] opened 2020-07-16 12:29 UTC
**Describe the bug**
Failed decompilation with Desolation update.

**Expected behavior**

**Steps To Reproduce**

**Specs (please complete the following information, if applicable):**
```
[INFO]: AMUMSS v3.6.0W
[INFO]: using Lua 5.3
[INFO]: on Windows 10 Pro 64bit with 12 logical CPUs
[INFO]: with MBINCompiler v2.51.0.1
```

**Additional Information**
```
[INFO]: Getting MODELS\PLANETS\BIOMES\UNDERWATER\MEDIUMPLANTS\MEDIUIMGLOWPLANT\ENTITIES\_BASE_1.ENTITY.MBIN from NMS source PAKs
[INFO]: Trying to decompile 
    [ERROR]: MBINCompiler = [[MbinException]: Failed to read TkAttachmentData from MBIN OR check your script,if it is a NMS file!]
    [PSARC]:  [The PAK will not include this EXML, if it is a NMS file!]
    [ERR]:   MBINCompiler =   [[InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0x650]
    [ERR]:   MBINCompiler =   [[INFO]: C:\Users\dheise\NMS\AMUMSS-3.6.0W-957-3-6-0W-1591222575\MODBUILDER\_TEMP\EXTRACTED\MODELS\PLANETS\BIOMES\UNDERWATER\MEDIUMPLANTS\MEDIUIMGLOWPLANT\ENTITIES\_BASE_1.ENTITY.MBIN]
    [ERR]:   MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	87068490DC83B1C1	template:	cTkAttachmentData]
    [ERR]:   MBINCompiler =      [at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)]
```

[REPORT.txt](https://github.com/monkeyman192/MBINCompiler/files/4931462/REPORT.txt)

**Comment by HolterPhylo** [comment] 2020-07-16 20:27
Please STOP creating Issues for MBINCompiler failure to decompile files for NMS 2.6.  MBINCompiler as NOT been updated yet!

**Comment by monkeyman192** [comment] 2020-07-16 23:18
Closing as a duplicate of #249

**Closed as completed by monkeyman192** 2020-07-16 23:18 UTC
Labels: bug

**Comment by daheise** [comment] 2020-07-17 12:49
Sorry, new to the NMS community, didn't know the process and got ahead of the [UPDATE] issue. Thanks for your work!
