### ISSUE TITLE
Failed decompilation with Desolation update: CONSUMABLEITEMTABLE.MBIN

### ISSUE THREAD

**Issue by Khaoz-Topsy** [monkeyman192/MBINCompiler#246] opened 2020-07-16 17:22 UTC
**Describe the bug**
Failed decompilation with Desolation update.

**Expected behavior**
Generate EXML from MBIN file

**Specs (please complete the following information, if applicable):**
 - MBINCompiler Version: v2.51.0-pre1
 - MBIN File: CONSUMABLEITEMTABLE.MBIN

**Additional Information**
```
[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: MBIN	version:	0.0.0.0	guid:	FDAAFD98379E000A	template:	cGcConsumableItemTable
  [EXPECTED INFO]: GUID: B6BD0D8EE97744B2
  

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed serializing GcConsumableItemTable to EXML.
[InvalidOperationException]: There was an error generating the XML document.
[ArgumentException]: '', hexadecimal value 0x01, is an invalid character.

   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)
```

**Comment by monkeyman192** [comment] 2020-07-16 23:14
Closing as a duplicate of #249

**Closed as completed by monkeyman192** 2020-07-16 23:14 UTC
Labels: bug
