### ISSUE TITLE
Failed decompilation with Desolation update: GCGAMEPLAYGLOBALS.GLOBAL.MBIN

### ISSUE THREAD

**Issue by daheise** [monkeyman192/MBINCompiler#241] opened 2020-07-16 12:33 UTC
**Describe the bug**
Failed decompilation with Desolation update.

**Expected behavior**

**Specs (please complete the following information, if applicable):**
```
[INFO]: AMUMSS v3.6.0W
[INFO]: using Lua 5.3
[INFO]: on Windows 10 Pro 64bit with 12 logical CPUs
[INFO]: with MBINCompiler v2.51.0.1
```

**Additional Information**
```[INFO]: ========================================================================================
[INFO]: Starting to process script #10 of 18 [ScanTimesAndRangeImprove.lua]
[INFO]: Copying script source to MOD
[INFO]: Getting GCGAMEPLAYGLOBALS.GLOBAL.MBIN from NMS source PAKs
[INFO]: Trying to decompile... 
    [WARNING]: MBINCompiler = [[WARN]: File not recognized. You may need to use an older version of MBINCompiler. OR check your script!]
    [WARN]:    MBINCompiler = [[INFO]: GCGAMEPLAYGLOBALS.GLOBAL.MBIN]
    [WARN]:    MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	70F37C71E79EB9C7	template:	cGcGameplayGlobals]
    [WARN]:    MBINCompiler =   [[EXPECTED INFO]: GUID: 54ACD3B81DA8ED08]
    [WARN]:    MBINCompiler = [[ERROR]: [MbinException]: Failed serializing GcGameplayGlobals to EXML.]
    [WARN]:    MBINCompiler =   [[InvalidOperationException]: There was an error generating the XML document.]
    [WARN]:    MBINCompiler =   [[ArgumentException]: '', hexadecimal value 0x01, is an invalid character.]
    [WARN]:    MBINCompiler =   [[INFO]: C:\Users\dheise\NMS\AMUMSS-3.6.0W-957-3-6-0W-1591222575\MODBUILDER\_TEMP\EXTRACTED\GCGAMEPLAYGLOBALS.GLOBAL.MBIN]
    [WARN]:    MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	70F37C71E79EB9C7	template:	cGcGameplayGlobals]
    [WARN]:    MBINCompiler =      [at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)]
    [WARN]:    MBINCompiler =      [at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)]
    [WARN]:    MBINCompiler =      [at System.Xml.XmlWellFormedWriter.WriteString(String text)]
    [WARN]:    MBINCompiler =      [at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)]
    [WARN]:    MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)]
    [WARN]:    MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)]
    [WARN]:    MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)]
    [WARN]:    MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)]
    [WARN]:    MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)]
    [WARN]:    MBINCompiler = [[INFO]: 1 FILES FAILED.]
    [WARN]:    MBINCompiler =   [[ERROR]: Failed serializing GcGameplayGlobals to EXML.]
    [WARN]:    MBINCompiler =   [[WARN]: File not recognized. You may need to use an older version of MBINCompiler.]
[INFO]: Trying to decompile 
    [ERROR]: MBINCompiler = [[MbinException]: Failed serializing GcGameplayGlobals to EXML OR check your script,if it is a NMS file!]
    [PSARC]:  [The PAK will not include this EXML, if it is a NMS file!]
    [ERR]:   MBINCompiler =   [[InvalidOperationException]: There was an error generating the XML document.]
    [ERR]:   MBINCompiler =   [[ArgumentException]: '', hexadecimal value 0x01, is an invalid character.]
    [ERR]:   MBINCompiler =   [[INFO]: C:\Users\dheise\NMS\AMUMSS-3.6.0W-957-3-6-0W-1591222575\MODBUILDER\_TEMP\EXTRACTED\GCGAMEPLAYGLOBALS.GLOBAL.MBIN]
    [ERR]:   MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	70F37C71E79EB9C7	template:	cGcGameplayGlobals]
    [ERR]:   MBINCompiler =      [at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)]
    [ERR]:   MBINCompiler =      [at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)]
    [ERR]:   MBINCompiler =      [at System.Xml.XmlWellFormedWriter.WriteString(String text)]
    [ERR]:   MBINCompiler =      [at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)]
    [ERR]:   MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)]
    [ERR]:   MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)]
    [ERR]:   MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)]
    [ERR]:   MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)]
    [ERR]:   MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)]
    [ERR]:   MBINCompiler = [[INFO]: 1 WARNINGS.]
    [ERR]:   MBINCompiler =   [[WARN]: File not recognized. You may need to use an older version of MBINCompiler.]
[INFO]: >>>>>>> Loaded script [ScanTimesAndRangeImprove.lua]
[INFO]: >>> GCGAMEPLAYGLOBALS.GLOBAL.EXML
    [ERROR]: file does not exist! See above for source...
```

[REPORT.txt](https://github.com/monkeyman192/MBINCompiler/files/4931462/REPORT.txt)

**Comment by monkeyman192** [comment] 2020-07-16 23:18
Closing as a duplicate of #249

**Closed as completed by monkeyman192** 2020-07-16 23:18 UTC
Labels: bug
