### ISSUE TITLE
GCGRAPHICSGLOBALS.GLOBAL.MBIN File not recognized [MBINCompiler v2.61.0.2]

### ISSUE THREAD

**Issue by willemjdg** [monkeyman192/MBINCompiler#254] opened 2020-07-20 19:32 UTC
GLOBAL file still header issue (Full compile report attached):

[INFO]: Getting GCGRAPHICSGLOBALS.GLOBAL.MBIN from NMS source PAKs
[INFO]: Trying to decompile... 
    [WARNING]: File not recognized= [[WARN]: File not recognized. You may need to use an older version of MBINCompiler. OR check your script!]
    [WARN]:    MBINCompiler = [[INFO]: GCGRAPHICSGLOBALS.GLOBAL.MBIN]
    [WARN]:    MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	EBAEB5139C17AAB	template:	cGcGraphicsGlobals]
    [WARN]:    MBINCompiler =   [[EXPECTED INFO]: GUID: 92D7F4BEEA8582C2]
    [WARN]:    MBINCompiler =   [[WARN]: File not recognized. You may need to use an older version of MBINCompiler.]

[REPORT.txt](https://github.com/monkeyman192/MBINCompiler/files/4949698/REPORT.txt)

**Comment by monkeyman192** [comment] 2020-07-20 21:39
Duplicate of #249

**Closed as completed by monkeyman192** 2020-07-20 21:39 UTC
Labels: bug
