### ISSUE TITLE
Failed decompilation with Desolation update: PROJECTILETABLE.MBIN

### ISSUE THREAD

**Issue by daheise** [monkeyman192/MBINCompiler#242] opened 2020-07-16 12:35 UTC
**Describe the bug**
Failed decompilation with Desolation update.

**Expected behavior**

**Specs (please complete the following information, if applicable):**
```
[INFO]: AMUMSS v3.6.0W
[INFO]: using Lua 5.3
[INFO]: on Windows 10 Pro 64bit with 12 logical CPUs
[INFO]: with MBINCompiler v2.51.0.1
```

**Additional Information**
```[INFO]: ========================================================================================
[INFO]: Starting to process script #11 of 18 [ShipGunTerrainDamage.lua]
[INFO]: Copying script source to MOD
[INFO]: Getting METADATA\PROJECTILES\PROJECTILETABLE.MBIN from NMS source PAKs
[INFO]: Trying to decompile... 
    [WARNING]: MBINCompiler = [[WARN]: File not recognized. You may need to use an older version of MBINCompiler. OR check your script!]
    [WARN]:    MBINCompiler =   [[INFO]: PROJECTILETABLE.MBIN]
    [WARN]:    MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	C1B22D1B7109D248	template:	cGcProjectileDataTable]
    [WARN]:    MBINCompiler =   [[EXPECTED INFO]: GUID: 3E54DAF2EF45ACEE]
    [WARN]:    MBINCompiler = [[ERROR]: [MbinException]: Failed to read GcProjectileDataTable from MBIN.]
    [WARN]:    MBINCompiler =   [[InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0x6D8]
    [WARN]:    MBINCompiler =   [[INFO]: C:\Users\dheise\NMS\AMUMSS-3.6.0W-957-3-6-0W-1591222575\MODBUILDER\_TEMP\EXTRACTED\METADATA\PROJECTILES\PROJECTILETABLE.MBIN]
    [WARN]:    MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	C1B22D1B7109D248	template:	cGcProjectileDataTable]
    [WARN]:    MBINCompiler =      [at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)]
    [WARN]:    MBINCompiler = [[INFO]: 1 FILES FAILED.]
    [WARN]:    MBINCompiler =   [[ERROR]: Failed to read GcProjectileDataTable from MBIN.]
    [WARN]:    MBINCompiler =   [[WARN]: File not recognized. You may need to use an older version of MBINCompiler.]
[INFO]: Trying to decompile 
    [ERROR]: MBINCompiler = [[MbinException]: Failed to read GcProjectileDataTable from MBIN OR check your script,if it is a NMS file!]
    [PSARC]:  [The PAK will not include this EXML, if it is a NMS file!]
    [ERR]:   MBINCompiler =   [[InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0x6D8]
    [ERR]:   MBINCompiler =   [[INFO]: C:\Users\dheise\NMS\AMUMSS-3.6.0W-957-3-6-0W-1591222575\MODBUILDER\_TEMP\EXTRACTED\METADATA\PROJECTILES\PROJECTILETABLE.MBIN]
    [ERR]:   MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	C1B22D1B7109D248	template:	cGcProjectileDataTable]
    [ERR]:   MBINCompiler =      [at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)]
    [ERR]:   MBINCompiler = [[INFO]: 1 WARNINGS.]
    [ERR]:   MBINCompiler =   [[WARN]: File not recognized. You may need to use an older version of MBINCompiler.]
[INFO]: >>>>>>> Loaded script [ShipGunTerrainDamage.lua]
[INFO]: >>> METADATA\PROJECTILES\PROJECTILETABLE.EXML
    [ERROR]: file does not exist! See above for source...
[INFO]: Combined Mod ACTIVE: Delaying Building MOD until the end...
[INFO]: Ending MBIN/PAK phase...
[INFO]: Ended script [ShipGunTerrainDamage.lua]
[INFO]: ========================================================================================
```

[REPORT.txt](https://github.com/monkeyman192/MBINCompiler/files/4931462/REPORT.txt)

**Comment by monkeyman192** [comment] 2020-07-16 23:17
Closing as a duplicate of #249

**Closed as completed by monkeyman192** 2020-07-16 23:17 UTC
Labels: bug
