### ISSUE TITLE
Failed decompilation with Desolation update: MULTIPLAYERMISSIONTABLE.MBIN

### ISSUE THREAD

**Issue by Khaoz-Topsy** [monkeyman192/MBINCompiler#248] opened 2020-07-16 17:24 UTC
**Describe the bug**
Failed decompilation with Desolation update.

**Expected behavior**
Generate EXML from MBIN file

**Specs (please complete the following information, if applicable):**
 - MBINCompiler Version: v2.51.0-pre1
 - MBIN File: MULTIPLAYERMISSIONTABLE.MBIN

**Additional Information**
```
[WARN]: File not recognized. You may need to use an older version of MBINCompiler.
  [INFO]: MBIN	version:	0.0.0.0	guid:	9C788541BC85212C	template:	cGcMissionTable
  [EXPECTED INFO]: GUID: 39853C1D772BC94B
  

[ERROR]: [AggregateException]: One or more errors occurred.
[MbinException]: Failed to read GcMissionTable from MBIN.
[InvalidListException]: Invalid list read, magic 00000000 expected xxxxxx01 at 0x8460

   at libMBIN.NMSTemplate.DeserializeGenericList(BinaryReader reader, NMSTemplate parent)
   at libMBIN.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at libMBIN.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)
   at libMBIN.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)
   at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)
```

**Comment by HolterPhylo** [comment] 2020-07-16 20:28
Please STOP creating Issues for MBINCompiler failure to decompile files for NMS 2.6.  MBINCompiler as NOT been updated yet!

**Comment by Khaoz-Topsy** [comment] 2020-07-16 20:33
Sorry! just following the previous issue declarations. I could not find a place where we could list the files that were giving issues after the NMS update. Also each file gave different stack traces and I assumed they were therefore different problems. Where would you prefer people report breaking changes after updates @HolterPhylo ?

**Comment by HolterPhylo** [comment] 2020-07-16 20:39
No need to report at this time.  We know MBINCompiler must be updated...

In a very short while, I will issue a list of all the internal structure that have changed / are new in NMS.exe and monkeyman192 will get to it when he can...

Thanks for your patience.  And don't be surprised if these issues are closed right away when monkeyman192 has a look...

**Comment by Khaoz-Topsy** [comment] 2020-07-16 20:46
No problem I sent him a message asking how he would like me to report the files that no longer deserialise, but it is obviously extremely early in the morning for him. Perhaps we could change the readme file to be more clear about when you would like issues to be created? At the moment it does not mention that we should not create issues for problem files when there is a recent update 🤔

**Comment by HolterPhylo** [comment] 2020-07-16 20:56
Lol,  I guess the wording did invite this type of "issue" (no pun intended) : 

SUBMITTING BUG REPORTS
"c) MBINCompiler has yes [sic] (should be 'yet') to be updated for the current game version of the data structure used by a particular file.
Check if there are any Open Issues for the file you are having problems with."

**Comment by Khaoz-Topsy** [comment] 2020-07-16 21:00
Yeah 😅. What if there was just one big issue created for each major update? Then it's easy to close once the MBinCompiler is updated for the latest NMS update? Although that is more effort than changing the readme 😅

**Comment by HolterPhylo** [comment] 2020-07-16 21:07
In a very short while, I will **_issue_** a list of all the internal structure that have changed / are new in NMS.exe and monkeyman192 will get to it when he can...

**Comment by Khaoz-Topsy** [comment] 2020-07-16 21:14
Aaah ok, so I was just too quick 😂

**Comment by HolterPhylo** [comment] 2020-07-16 21:33
See Issue #249 for all the files that need updating for MBINCompiler 2.60.0.0

**Comment by Khaoz-Topsy** [comment] 2020-07-16 21:38
That is one massive list... is it common for so many files to break after an update? 😐

**Comment by monkeyman192** [comment] 2020-07-16 23:14
Closing as a duplicate of #249

**Closed as completed by monkeyman192** 2020-07-16 23:14 UTC
Labels: bug
