### ISSUE TITLE
 Failed decompilation with Desolation update: REWARDTABLE.MBIN

### ISSUE THREAD

**Issue by daheise** [monkeyman192/MBINCompiler#240] opened 2020-07-16 12:32 UTC
**Describe the bug**
Failed decompilation with Desolation update.

**Expected behavior**

**Specs (please complete the following information, if applicable):**
```
[INFO]: AMUMSS v3.6.0W
[INFO]: using Lua 5.3
[INFO]: on Windows 10 Pro 64bit with 12 logical CPUs
[INFO]: with MBINCompiler v2.51.0.1
```

**Additional Information**
```
[INFO]: Starting to process script #4 of 18 [LearnMoreWords.lua]
[INFO]: Copying script source to MOD
[INFO]: Getting METADATA\REALITY\TABLES\REWARDTABLE.MBIN from NMS source PAKs
[INFO]: Trying to decompile 
    [ERROR]: MBINCompiler = [[MbinException]: Failed to read GcRewardTable from MBIN OR check your script,if it is a NMS file!]
    [PSARC]:  [The PAK will not include this EXML, if it is a NMS file!]
    [ERR]:   MBINCompiler =   [[DeserializeTemplateException]: Failed to deserialize template cGcRewardSystemSpecificProductFromList!]
    [ERR]:   MBINCompiler =   [[INFO]: C:\Users\dheise\NMS\AMUMSS-3.6.0W-957-3-6-0W-1591222575\MODBUILDER\_TEMP\EXTRACTED\METADATA\REALITY\TABLES\REWARDTABLE.MBIN]
    [ERR]:   MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	A81469E1E461F02D	template:	cGcRewardTable]
    [ERR]:   MBINCompiler =      [at libMBIN.NMSTemplate.DeserializeValue(BinaryReader reader, Type field, NMSAttribute settings, Int64 templatePosition, FieldInfo fieldInfo, NMSTemplate parent)]
    [ERR]:   MBINCompiler =      [at libMBIN.NMSTemplate.DeserializeBinaryTemplate(BinaryReader reader, String templateName)]
    [ERR]:   MBINCompiler =      [at libMBIN.NMSTemplate.DeserializeList[T](BinaryReader reader, FieldInfo field, NMSAttribute settings, Int64 templateStartOffset, NMSTemplate parent)]
[INFO]: >>>>>>> Loaded script [LearnMoreWords.lua]
[INFO]: >>> METADATA\REALITY\TABLES\REWARDTABLE.EXML
    [ERROR]: file does not exist! See above for source...
```

[REPORT.txt](https://github.com/monkeyman192/MBINCompiler/files/4931462/REPORT.txt)

**Comment by monkeyman192** [comment] 2020-07-16 23:18
Closing as a duplicate of #249

**Closed as completed by monkeyman192** 2020-07-16 23:18 UTC
Labels: bug
