### ISSUE TITLE
Failed decompilation with Desolation update: GCUIGLOBALS.GLOBAL.MBIN

### ISSUE THREAD

**Issue by daheise** [monkeyman192/MBINCompiler#243] opened 2020-07-16 12:36 UTC
**Describe the bug**
Failed decompilation with Desolation update.

**Expected behavior**

**Specs (please complete the following information, if applicable):**
```
[INFO]: AMUMSS v3.6.0W
[INFO]: using Lua 5.3
[INFO]: on Windows 10 Pro 64bit with 12 logical CPUs
[INFO]: with MBINCompiler v2.51.0.1
```

**Additional Information**
```
[INFO]: ========================================================================================
[INFO]: Starting to process script #13 of 18 [SpeedIncreaseActions.lua]
[INFO]: Copying script source to MOD
[INFO]: Getting GCUIGLOBALS.GLOBAL.MBIN from NMS source PAKs
[INFO]: Trying to decompile... 
    [WARNING]: MBINCompiler = [[WARN]: File not recognized. You may need to use an older version of MBINCompiler. OR check your script!]
    [WARN]:    MBINCompiler = [[INFO]: GCUIGLOBALS.GLOBAL.MBIN]
    [WARN]:    MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	E987C1CAE3F38E3D	template:	cGcUIGlobals]
    [WARN]:    MBINCompiler =   [[EXPECTED INFO]: GUID: 66642D0536FF1625]
    [WARN]:    MBINCompiler = [[ERROR]: [MbinException]: Failed serializing GcUIGlobals to EXML.]
    [WARN]:    MBINCompiler =   [[InvalidOperationException]: There was an error generating the XML document.]
    [WARN]:    MBINCompiler =   [[ArgumentException]: '', hexadecimal value 0x12, is an invalid character.]
    [WARN]:    MBINCompiler =   [[INFO]: C:\Users\dheise\NMS\AMUMSS-3.6.0W-957-3-6-0W-1591222575\MODBUILDER\_TEMP\EXTRACTED\GCUIGLOBALS.GLOBAL.MBIN]
    [WARN]:    MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	E987C1CAE3F38E3D	template:	cGcUIGlobals]
    [WARN]:    MBINCompiler =      [at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)]
    [WARN]:    MBINCompiler =      [at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)]
    [WARN]:    MBINCompiler =      [at System.Xml.XmlWellFormedWriter.WriteString(String text)]
    [WARN]:    MBINCompiler =      [at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)]
    [WARN]:    MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)]
    [WARN]:    MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)]
    [WARN]:    MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)]
    [WARN]:    MBINCompiler = [[INFO]: 1 FILES FAILED.]
    [WARN]:    MBINCompiler =   [[ERROR]: Failed serializing GcUIGlobals to EXML.]
    [WARN]:    MBINCompiler =   [[WARN]: File not recognized. You may need to use an older version of MBINCompiler.]
[INFO]: Trying to decompile 
    [ERROR]: MBINCompiler = [[MbinException]: Failed serializing GcUIGlobals to EXML OR check your script,if it is a NMS file!]
    [PSARC]:  [The PAK will not include this EXML, if it is a NMS file!]
    [ERR]:   MBINCompiler =   [[InvalidOperationException]: There was an error generating the XML document.]
    [ERR]:   MBINCompiler =   [[ArgumentException]: '', hexadecimal value 0x12, is an invalid character.]
    [ERR]:   MBINCompiler =   [[INFO]: C:\Users\dheise\NMS\AMUMSS-3.6.0W-957-3-6-0W-1591222575\MODBUILDER\_TEMP\EXTRACTED\GCUIGLOBALS.GLOBAL.MBIN]
    [ERR]:   MBINCompiler =   [[INFO]: MBIN	version:	0.0.0.0	guid:	E987C1CAE3F38E3D	template:	cGcUIGlobals]
    [ERR]:   MBINCompiler =      [at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)]
    [ERR]:   MBINCompiler =      [at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)]
    [ERR]:   MBINCompiler =      [at System.Xml.XmlWellFormedWriter.WriteString(String text)]
    [ERR]:   MBINCompiler =      [at System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)]
    [ERR]:   MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)]
    [ERR]:   MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)]
    [ERR]:   MBINCompiler =      [at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)]
    [ERR]:   MBINCompiler = [[INFO]: 1 WARNINGS.]
    [ERR]:   MBINCompiler =   [[WARN]: File not recognized. You may need to use an older version of MBINCompiler.]
[INFO]: >>>>>>> Loaded script [SpeedIncreaseActions.lua]
[INFO]: >>> GCUIGLOBALS.GLOBAL.EXML
    [ERROR]: file does not exist! See above for source...
[INFO]: Combined Mod ACTIVE: Delaying Building MOD until the end...
[INFO]: Ending MBIN/PAK phase...
[INFO]: Ended script [SpeedIncreaseActions.lua]
[INFO]: ========================================================================================

```

[REPORT.txt](https://github.com/monkeyman192/MBINCompiler/files/4931462/REPORT.txt)

**Comment by monkeyman192** [comment] 2020-07-16 23:17
Closing as a duplicate of #249

**Closed as completed by monkeyman192** 2020-07-16 23:17 UTC
Labels: bug
